// src/components/ActionsMenu.svelte
<script lang="ts">
import {
  ClipboardCopy,
  FileDown,
  FileText,
  MoreHorizontal,
  RefreshCw,
  Settings,
} from "lucide-svelte";
import { t } from "../stores/locale.svelte";
import RawModal from "./RawModal.svelte";
import SettingsModal from "./SettingsModal.svelte";
import Button from "./ui/Button.svelte";
import DropdownMenu from "./ui/DropdownMenu.svelte";
import DropdownMenuItem from "./ui/DropdownMenuItem.svelte";
import DropdownMenuSeparator from "./ui/DropdownMenuSeparator.svelte";

interface Props {
  commentCount: number;
  oncopyall: () => void;
  onexportjson: () => void;
  onreload: () => void;
}

let { commentCount, oncopyall, onexportjson, onreload }: Props = $props();

let menuOpen = $state(false);
let rawModalOpen = $state(false);
let settingsOpen = $state(false);
</script>

<DropdownMenu bind:open={menuOpen} align="end" contentClass="min-w-[160px]">
  {#snippet trigger()}
    <Button
      variant="ghost"
      size="icon"
      class="size-7"
      title={t("actions.ariaLabel")}
    >
      <MoreHorizontal class="w-4 h-4" />
    </Button>
  {/snippet}

  <DropdownMenuItem
    onselect={() => {
      settingsOpen = true;
      menuOpen = false;
    }}
  >
    <Settings />
    {t("actions.settings")}
  </DropdownMenuItem>
  <DropdownMenuSeparator />
  <DropdownMenuItem
    onselect={() => {
      onreload();
      menuOpen = false;
    }}
  >
    <RefreshCw />
    {t("actions.reload")}
  </DropdownMenuItem>
  {#if commentCount > 0}
    <DropdownMenuItem
      onselect={() => {
        oncopyall();
        menuOpen = false;
      }}
    >
      <ClipboardCopy />
      {t("actions.copyAll")}
    </DropdownMenuItem>
    <DropdownMenuItem
      onselect={() => {
        onexportjson();
        menuOpen = false;
      }}
    >
      <FileDown />
      {t("actions.exportJson")}
    </DropdownMenuItem>
    <DropdownMenuItem
      onselect={() => {
        rawModalOpen = true;
        menuOpen = false;
      }}
    >
      <FileText />
      {t("actions.viewRaw")}
    </DropdownMenuItem>
  {/if}
</DropdownMenu>

<RawModal bind:open={rawModalOpen} onclose={() => (rawModalOpen = false)} />
<SettingsModal bind:open={settingsOpen} onclose={() => (settingsOpen = false)} />

// src/components/ActionsMenu.tsx
import {
  ClipboardCopy,
  FileDown,
  FileText,
  MoreHorizontal,
  RefreshCw,
  Settings,
} from "lucide-react";
import { useState } from "react";
import { useCommentData } from "../contexts/CommentContext";
import { useLocale } from "../contexts/LocaleContext";
import { RawModal } from "./RawModal";
import { SettingsModal } from "./SettingsModal";
import { Button } from "./ui/Button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "./ui/DropdownMenu";

interface ActionsMenuProps {
  onCopyAll: () => void;
  onExportJson: () => void;
  onReload: () => void;
}

export function ActionsMenu({
  onCopyAll,
  onExportJson,
  onReload,
}: ActionsMenuProps) {
  const { commentCount } = useCommentData();
  const { t } = useLocale();

  const [menuOpen, setMenuOpen] = useState(false);
  const [rawModalOpen, setRawModalOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);

  return (
    <>
      <DropdownMenu open={menuOpen} onOpenChange={setMenuOpen}>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="icon"
            className="size-7"
            aria-label={t("actions.ariaLabel")}
          >
            <MoreHorizontal className="w-4 h-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="min-w-[160px]">
          <DropdownMenuItem onSelect={() => setSettingsOpen(true)}>
            <Settings />
            {t("actions.settings")}
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onSelect={() => onReload()}>
            <RefreshCw />
            {t("actions.reload")}
          </DropdownMenuItem>
          {commentCount > 0 && (
            <>
              <DropdownMenuItem onSelect={() => onCopyAll()}>
                <ClipboardCopy />
                {t("actions.copyAll")}
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={() => onExportJson()}>
                <FileDown />
                {t("actions.exportJson")}
              </DropdownMenuItem>
              <DropdownMenuItem onSelect={() => setRawModalOpen(true)}>
                <FileText />
                {t("actions.viewRaw")}
              </DropdownMenuItem>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <RawModal isOpen={rawModalOpen} onClose={() => setRawModalOpen(false)} />

      <SettingsModal
        isOpen={settingsOpen}
        onClose={() => setSettingsOpen(false)}
      />
    </>
  );
}
