// src/components/CommentListItem.tsx
import { useState } from "react";
import { useCommentContext } from "../contexts/CommentContext";
import { cn } from "../lib/utils";
import type { Comment } from "../types";
import { InlineEditor } from "./InlineEditor";
import { ActionBar } from "./ui/action-bar";
import { ActionLink } from "./ui/action-link";
import { Text } from "./ui/text";

interface CommentListItemProps {
  comment: Comment;
  /** Called after navigation actions (Go to, Re-anchor) to close parent dropdown */
  onAction?: () => void;
}

export function CommentListItem({ comment, onAction }: CommentListItemProps) {
  const { editComment, deleteComment, navigateToComment, startReanchor } =
    useCommentContext();

  const [isEditing, setIsEditing] = useState(false);

  const isUnresolved = comment.anchorConfidence === "unresolved";
  const canGoTo = !isUnresolved;

  const handleGoTo = () => {
    navigateToComment(comment.id);
    onAction?.();
  };

  const handleReanchor = () => {
    startReanchor(comment.id);
    onAction?.();
  };

  return (
    <div
      className={cn(
        "group px-3 py-2 border-b border-zinc-100 last:border-b-0",
        isUnresolved && "opacity-50",
      )}
    >
      <div className="flex items-center gap-1.5 mb-1">
        <Text variant="caption" asChild>
          <span className="font-serif italic line-clamp-1">
            "{comment.selectedText}"
          </span>
        </Text>
        {isUnresolved && (
          <Text variant="caption" asChild>
            <span className="shrink-0">· unresolved</span>
          </Text>
        )}
      </div>

      {isEditing ? (
        <InlineEditor
          initialText={comment.comment}
          onSave={(text) => {
            editComment(comment.id, text);
            setIsEditing(false);
          }}
          onCancel={() => setIsEditing(false)}
          className="font-serif"
        />
      ) : (
        <>
          <Text variant="body" asChild>
            <p className="font-serif line-clamp-2">{comment.comment}</p>
          </Text>

          <ActionBar className="gap-3 mt-1.5">
            <ActionLink onClick={() => setIsEditing(true)}>Edit</ActionLink>
            <ActionLink onClick={() => deleteComment(comment.id)}>
              Delete
            </ActionLink>
            {canGoTo && <ActionLink onClick={handleGoTo}>Go to</ActionLink>}
            {isUnresolved && (
              <ActionLink onClick={handleReanchor}>Re-anchor</ActionLink>
            )}
          </ActionBar>
        </>
      )}
    </div>
  );
}

// src/components/CommentListItem.svelte
<script lang="ts">
import { cn } from "../lib/utils";
import type { Comment } from "../schema";
import { t } from "../stores/locale.svelte";
import ActionLink from "./ui/ActionLink.svelte";
import Text from "./ui/Text.svelte";
import InlineEditor from "./InlineEditor.svelte";

interface Props {
  comment: Comment;
  onaction?: () => void;
  onedit: (id: string, newText: string) => void;
  ondelete: (id: string) => void;
  onnavigate: (id: string) => void;
  onstartreanchor: (id: string) => void;
}

let {
  comment,
  onaction,
  onedit,
  ondelete,
  onnavigate,
  onstartreanchor,
}: Props = $props();

let isEditing = $state(false);

let isUnresolved = $derived(comment.anchorConfidence === "unresolved");
let canGoTo = $derived(!isUnresolved);

function handleGoTo() {
  onnavigate(comment.id);
  onaction?.();
}

function handleReanchor() {
  onstartreanchor(comment.id);
  onaction?.();
}
</script>

<div
  class={cn(
    "group px-3 py-2 border-b border-zinc-100 dark:border-zinc-800 last:border-b-0",
    isUnresolved && "opacity-50",
  )}
>
  <div class="flex items-center gap-1.5 mb-1">
    <Text variant="caption" as="span" class="italic line-clamp-1">
      "{comment.selectedText}"
    </Text>
    {#if isUnresolved}
      <Text variant="caption" as="span" class="shrink-0">
        · {t("commentList.unresolved")}
      </Text>
    {/if}
  </div>

  {#if isEditing}
    <InlineEditor
      initialText={comment.comment}
      onsave={(text) => {
        onedit(comment.id, text);
        isEditing = false;
      }}
      oncancel={() => (isEditing = false)}
    />
  {:else}
    <Text variant="body" class="line-clamp-2">
      {comment.comment}
    </Text>

    <div
      class="flex items-center text-xs text-zinc-400 opacity-0 group-hover:opacity-100 transition-opacity gap-3 mt-1.5"
    >
      <ActionLink onclick={() => (isEditing = true)}>
        {t("commentList.edit")}
      </ActionLink>
      <ActionLink onclick={() => ondelete(comment.id)}>
        {t("commentList.delete")}
      </ActionLink>
      {#if canGoTo}
        <ActionLink onclick={handleGoTo}>
          {t("commentList.goTo")}
        </ActionLink>
      {/if}
      {#if isUnresolved}
        <ActionLink onclick={handleReanchor}>
          {t("commentList.reanchor")}
        </ActionLink>
      {/if}
    </div>
  {/if}
</div>
