// src/components/comments/CommentManager.tsx
import { Copy, Trash2 } from "lucide-react";
import { useCallback, useState } from "react";
import { toast } from "sonner";
import {
  useCommentActions,
  useCommentData,
} from "../../contexts/CommentContext";
import { useLocale } from "../../contexts/LocaleContext";
import { generatePrompt } from "../../lib/export";
import { useAppStore } from "../../store";
import { Button } from "../ui/Button";
import { Text } from "../ui/Text";
import { CommentListItem } from "./CommentListItem";

interface CommentManagerProps {
  onClose: () => void;
}

export function CommentManager({ onClose }: CommentManagerProps) {
  const { t } = useLocale();
  const { comments } = useCommentData();
  const { deleteAll } = useCommentActions();
  const fileName = useAppStore(
    (s) => s.getActiveDocumentState()?.document.fileName ?? "",
  );

  const copyAll = useCallback(() => {
    const text = generatePrompt(comments, fileName);
    navigator.clipboard.writeText(text);
    toast.success(t("toast.copiedAllComments"));
  }, [comments, fileName, t]);
  const [confirmingDelete, setConfirmingDelete] = useState(false);

  const unresolvedCount = comments.filter(
    (c) => c.anchorConfidence === "unresolved",
  ).length;
  const resolvedCount = comments.length - unresolvedCount;

  const sortedComments = [...comments].sort((a, b) => {
    const aUnresolved = a.anchorConfidence === "unresolved";
    const bUnresolved = b.anchorConfidence === "unresolved";
    if (aUnresolved === bUnresolved) return 0;
    return aUnresolved ? 1 : -1;
  });

  return (
    <>
      {confirmingDelete ? (
        <div className="px-3 py-2 border-b border-zinc-100">
          <Text variant="caption" className="mb-1.5">
            {t("commentManager.deleteAllConfirm", { count: comments.length })}
          </Text>
          <div className="flex gap-3">
            <Button
              variant="link"
              size="sm"
              className="text-red-600 hover:text-red-700 h-auto p-0 text-xs"
              onClick={() => {
                deleteAll();
                onClose();
              }}
            >
              {t("commentManager.delete")}
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-auto p-0 text-xs"
              onClick={() => setConfirmingDelete(false)}
            >
              {t("commentManager.cancel")}
            </Button>
          </div>
        </div>
      ) : (
        <Text
          variant="caption"
          as="div"
          className="flex items-center justify-between px-3 py-2 border-b border-zinc-100"
        >
          <span>
            {resolvedCount}
            {unresolvedCount > 0 && (
              <span>
                {" "}
                · {unresolvedCount} {t("commentManager.unresolved")}
              </span>
            )}
          </span>
          <span className="flex items-center gap-1">
            <button
              type="button"
              className="p-1 rounded hover:bg-zinc-100 text-zinc-400 hover:text-zinc-600 transition-colors"
              onClick={copyAll}
              title={t("commentManager.copyAllTitle")}
            >
              <Copy size={13} />
            </button>
            <button
              type="button"
              className="p-1 rounded hover:bg-zinc-100 text-zinc-400 hover:text-red-500 transition-colors"
              onClick={() => setConfirmingDelete(true)}
              title={t("commentManager.deleteAllTitle")}
            >
              <Trash2 size={13} />
            </button>
          </span>
        </Text>
      )}

      <div className="overflow-y-auto max-h-80">
        {sortedComments.length === 0 ? (
          <Text variant="caption" as="div" className="px-3 py-4 text-center">
            {t("commentManager.noComments")}
          </Text>
        ) : (
          sortedComments.map((comment) => (
            <CommentListItem
              key={comment.id}
              comment={comment}
              onAction={onClose}
            />
          ))
        )}
      </div>
    </>
  );
}

// src/components/CommentManager.svelte
<script lang="ts">
import { Copy, Trash2 } from "lucide-svelte";
import { generatePrompt } from "../lib/export";
import type { Comment } from "../schema";
import { t } from "../stores/locale.svelte";
import CommentListItem from "./CommentListItem.svelte";
import Button from "./ui/Button.svelte";
import Text from "./ui/Text.svelte";

interface Props {
  comments: Comment[];
  fileName: string;
  onclose: () => void;
  onedit: (id: string, newText: string) => void;
  ondelete: (id: string) => void;
  ondeleteall: () => void;
  onnavigate: (id: string) => void;
  onstartreanchor: (id: string) => void;
}

let {
  comments,
  fileName,
  onclose,
  onedit,
  ondelete,
  ondeleteall,
  onnavigate,
  onstartreanchor,
}: Props = $props();

let confirmingDelete = $state(false);

let unresolvedCount = $derived(
  comments.filter((c) => c.anchorConfidence === "unresolved").length,
);
let resolvedCount = $derived(comments.length - unresolvedCount);

let sortedComments = $derived(
  [...comments].sort((a, b) => {
    const aUnresolved = a.anchorConfidence === "unresolved";
    const bUnresolved = b.anchorConfidence === "unresolved";
    if (aUnresolved === bUnresolved) return 0;
    return aUnresolved ? 1 : -1;
  }),
);

function copyAll() {
  const text = generatePrompt(comments, fileName);
  navigator.clipboard.writeText(text);
}
</script>

{#if confirmingDelete}
  <div class="px-3 py-2 border-b border-zinc-100">
    <Text variant="caption" class="mb-1.5">
      {t("commentManager.deleteAllConfirm", { count: comments.length })}
    </Text>
    <div class="flex gap-3">
      <Button
        variant="link"
        size="sm"
        class="text-red-600 hover:text-red-700 h-auto p-0 text-xs"
        onclick={() => {
          ondeleteall();
          onclose();
        }}
      >
        {t("commentManager.delete")}
      </Button>
      <Button
        variant="ghost"
        size="sm"
        class="h-auto p-0 text-xs"
        onclick={() => (confirmingDelete = false)}
      >
        {t("commentManager.cancel")}
      </Button>
    </div>
  </div>
{:else}
  <Text variant="caption" as="div" class="flex items-center justify-between px-3 py-2 border-b border-zinc-100">
    <span>
      {resolvedCount}
      {#if unresolvedCount > 0}
        <span>
          {" "}· {unresolvedCount} {t("commentManager.unresolved")}
        </span>
      {/if}
    </span>
    <span class="flex items-center gap-1">
      <button
        type="button"
        class="p-1 rounded hover:bg-zinc-100 text-zinc-400 hover:text-zinc-600 transition-colors"
        onclick={copyAll}
        title={t("commentManager.copyAllTitle")}
      >
        <Copy size={13} />
      </button>
      <button
        type="button"
        class="p-1 rounded hover:bg-zinc-100 text-zinc-400 hover:text-red-500 transition-colors"
        onclick={() => (confirmingDelete = true)}
        title={t("commentManager.deleteAllTitle")}
      >
        <Trash2 size={13} />
      </button>
    </span>
  </Text>
{/if}

<div class="overflow-y-auto max-h-80">
  {#if sortedComments.length === 0}
    <Text variant="caption" as="div" class="px-3 py-4 text-center">
      {t("commentManager.noComments")}
    </Text>
  {:else}
    {#each sortedComments as comment (comment.id)}
      <CommentListItem
        {comment}
        onaction={onclose}
        {onedit}
        {ondelete}
        {onnavigate}
        {onstartreanchor}
      />
    {/each}
  {/if}
</div>
