// src/components/comments/CommentBadge.tsx
import { useState } from "react";
import { useCommentContext } from "../../contexts/CommentContext";
import { useLocale } from "../../contexts/LocaleContext";
import { cn } from "../../lib/utils";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "../ui/DropdownMenu";
import { CommentManager } from "./CommentManager";

export function CommentBadge() {
  const { t } = useLocale();
  const { commentCount } = useCommentContext();

  const [commentsOpen, setCommentsOpen] = useState(false);

  if (commentCount === 0) return null;

  return (
    <DropdownMenu open={commentsOpen} onOpenChange={setCommentsOpen}>
      <DropdownMenuTrigger asChild>
        <button
          type="button"
          className={cn(
            "inline-flex items-center gap-1 text-xs tabular-nums select-none transition-colors",
            commentsOpen
              ? "text-zinc-600"
              : "text-zinc-400 hover:text-zinc-600",
          )}
          title={
            commentCount === 1
              ? t("commentBadge.title", { count: commentCount })
              : t("commentBadge.titlePlural", { count: commentCount })
          }
        >
          <span className="text-zinc-300">·</span>
          {commentCount}
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="end"
        className="w-80 max-h-96 overflow-hidden p-0"
      >
        <CommentManager onClose={() => setCommentsOpen(false)} />
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// src/components/CommentBadge.svelte
<script lang="ts">
import { cn } from "../lib/utils";
import { app } from "../stores/app.svelte";
import { t } from "../stores/locale.svelte";
import CommentManager from "./CommentManager.svelte";
import DropdownMenu from "./ui/DropdownMenu.svelte";

interface Props {
  filePath: string;
  onnavigate: (id: string) => void;
}

let { filePath, onnavigate }: Props = $props();

let commentsOpen = $state(false);
let commentCount = $derived(app.documents.get(filePath)?.comments.length ?? 0);
</script>

{#if commentCount > 0}
  <DropdownMenu
    bind:open={commentsOpen}
    align="end"
    contentClass="w-80 max-h-96 overflow-hidden p-0"
  >
    {#snippet trigger()}
      <button
        type="button"
        class={cn(
          "inline-flex items-center gap-1 text-xs tabular-nums select-none transition-colors",
          commentsOpen
            ? "text-zinc-600"
            : "text-zinc-400 hover:text-zinc-600",
        )}
        title={commentCount === 1
          ? t("commentBadge.title", { count: commentCount })
          : t("commentBadge.titlePlural", { count: commentCount })}
      >
        <span class="text-zinc-300">·</span>
        {commentCount}
      </button>
    {/snippet}

    <CommentManager
      {filePath}
      onclose={() => (commentsOpen = false)}
      {onnavigate}
    />
  </DropdownMenu>
{/if}
