// src/components/RawModal.svelte
<script lang="ts">
import { Copy } from "lucide-svelte";
import { app } from "../stores/app.svelte";
import { t } from "../stores/locale.svelte";
import Button from "./ui/Button.svelte";
import Dialog from "./ui/Dialog.svelte";
import Text from "./ui/Text.svelte";

interface Props {
  open: boolean;
  onclose: () => void;
}

let { open = $bindable(false), onclose }: Props = $props();

type ModalState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; error: string }
  | { status: "empty"; path: string }
  | { status: "success"; content: string; path: string };

let modalState = $state<ModalState>({ status: "idle" });

$effect(() => {
  if (!open) {
    modalState = { status: "idle" };
    return;
  }

  modalState = { status: "loading" };

  const query = app.activeDocumentPath
    ? `?path=${encodeURIComponent(app.activeDocumentPath)}`
    : "";

  fetch(`/api/comments/raw${query}`)
    .then((response) => {
      if (!response.ok) {
        throw new Error("Failed to fetch raw comments");
      }
      return response.json();
    })
    .then((result) => {
      if (result.content === null) {
        modalState = { status: "empty", path: result.path };
      } else {
        modalState = {
          status: "success",
          content: result.content,
          path: result.path,
        };
      }
    })
    .catch((err) => {
      modalState = {
        status: "error",
        error: err instanceof Error ? err.message : "Unknown error",
      };
    });
});

async function handleCopy() {
  if (modalState.status !== "success") return;

  try {
    await navigator.clipboard.writeText(modalState.content);
  } catch {}
}
</script>

<Dialog bind:open {onclose} contentClass="max-w-2xl max-h-[80vh]">
  {#snippet header()}
    {t("rawModal.title")}
  {/snippet}

  {#snippet headerActions()}
    {#if modalState.status === "success"}
      <Button
        variant="ghost"
        size="icon"
        class="size-7"
        onclick={handleCopy}
        title={t("rawModal.copyTitle")}
      >
        <Copy class="w-4 h-4" />
      </Button>
    {/if}
  {/snippet}

  {#if modalState.status === "success" || modalState.status === "empty"}
    <div
      class="px-4 py-2 border-b border-zinc-50 dark:border-zinc-800 text-xs text-zinc-400 dark:text-zinc-500 font-mono truncate -mt-4 -mx-4 mb-4"
    >
      {modalState.path}
    </div>
  {/if}

  {#if modalState.status === "loading"}
    <Text variant="caption" class="text-center py-8">
      {t("rawModal.loading")}
    </Text>
  {/if}

  {#if modalState.status === "error"}
    <Text variant="body" class="text-red-500 text-center py-8">
      {modalState.error}
    </Text>
  {/if}

  {#if modalState.status === "empty"}
    <Text variant="caption" class="text-center py-8">
      {t("rawModal.noComments")}
    </Text>
  {/if}

  {#if modalState.status === "success"}
    <Text
      variant="body"
      as="pre"
      class="text-xs font-mono whitespace-pre-wrap break-words leading-relaxed"
    >
      {modalState.content}
    </Text>
  {/if}
</Dialog>

// src/components/RawModal.tsx
import { Copy } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocale } from "../contexts/LocaleContext";
import { useAppStore } from "../store";
import { Button } from "./ui/Button";
import {
  Dialog,
  DialogBody,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "./ui/Dialog";
import { Text } from "./ui/Text";

interface RawModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type ModalState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; error: string }
  | { status: "empty"; path: string }
  | { status: "success"; content: string; path: string };

export function RawModal({ isOpen, onClose }: RawModalProps) {
  const { t } = useLocale();
  const [state, setState] = useState<ModalState>({ status: "idle" });
  const activeDocumentPath = useAppStore((s) => s.activeDocumentPath);

  // Fetch raw comments when modal opens
  useEffect(() => {
    if (!isOpen) {
      setState({ status: "idle" });
      return;
    }

    setState({ status: "loading" });

    const fetchRawComments = async () => {
      try {
        const query = activeDocumentPath
          ? `?path=${encodeURIComponent(activeDocumentPath)}`
          : "";
        const response = await fetch(`/api/comments/raw${query}`);
        if (!response.ok) {
          throw new Error("Failed to fetch raw comments");
        }
        const result = await response.json();
        if (result.content === null) {
          setState({ status: "empty", path: result.path });
        } else {
          setState({
            status: "success",
            content: result.content,
            path: result.path,
          });
        }
      } catch (err) {
        setState({
          status: "error",
          error: err instanceof Error ? err.message : "Unknown error",
        });
      }
    };

    fetchRawComments();
  }, [isOpen, activeDocumentPath]);

  const handleCopy = useCallback(async () => {
    if (state.status !== "success") return;

    try {
      await navigator.clipboard.writeText(state.content);
      toast.success(t("rawModal.copiedToClipboard"));
    } catch {
      toast.error(t("rawModal.failedToCopy"));
    }
  }, [state, t]);

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <DialogContent className="max-w-2xl max-h-[80vh]" onClose={onClose}>
        <DialogHeader>
          <DialogTitle>{t("rawModal.title")}</DialogTitle>
          {state.status === "success" && (
            <Button
              variant="ghost"
              size="icon"
              className="size-7"
              onClick={handleCopy}
              title={t("rawModal.copyTitle")}
            >
              <Copy className="w-4 h-4" />
            </Button>
          )}
        </DialogHeader>

        {(state.status === "success" || state.status === "empty") && (
          <div className="px-4 py-2 border-b border-zinc-50 dark:border-zinc-800 text-xs text-zinc-400 dark:text-zinc-500 font-mono truncate">
            {state.path}
          </div>
        )}

        <DialogBody>
          {state.status === "loading" && (
            <Text variant="caption" className="text-center py-8">
              {t("rawModal.loading")}
            </Text>
          )}

          {state.status === "error" && (
            <Text variant="body" className="text-red-500 text-center py-8">
              {state.error}
            </Text>
          )}

          {state.status === "empty" && (
            <Text variant="caption" className="text-center py-8">
              {t("rawModal.noComments")}
            </Text>
          )}

          {state.status === "success" && (
            <Text variant="body" as="pre" className="text-xs font-mono whitespace-pre-wrap break-words leading-relaxed">
              {state.content}
            </Text>
          )}
        </DialogBody>
      </DialogContent>
    </Dialog>
  );
}
