// src/components/TableOfContents.svelte
<script lang="ts">
import type { Heading } from "../lib/headings";
import { cn } from "../lib/utils";
import { FontFamilies } from "../schema";
import { settings } from "../stores/settings.svelte";

interface Props {
  headings: Heading[];
  activeId: string | null;
  onheadingclick: (id: string) => void;
}

let { headings, activeId, onheadingclick }: Props = $props();

let fontClass = $derived(
  settings.fontFamily === FontFamilies.SANS_SERIF ? "font-sans" : "font-serif",
);

let expandedH2s = $state(new Set<string>());

let h2sWithChildren = $derived.by(() => {
  const result = new Set<string>();
  let currentH2: string | null = null;

  for (const heading of headings) {
    if (heading.level === 2) {
      currentH2 = heading.id;
    } else if (heading.level > 2 && currentH2) {
      result.add(currentH2);
    } else if (heading.level === 1) {
      currentH2 = null;
    }
  }
  return result;
});

let visibleHeadings = $derived.by(() => {
  let currentH2: string | null = null;

  return headings.filter((heading) => {
    if (heading.level <= 2) {
      if (heading.level === 2) {
        currentH2 = heading.id;
      } else {
        currentH2 = null;
      }
      return true;
    }

    return currentH2 !== null && expandedH2s.has(currentH2);
  });
});

function toggleH2(id: string) {
  const next = new Set(expandedH2s);
  if (next.has(id)) {
    next.delete(id);
  } else {
    next.add(id);
  }
  expandedH2s = next;
}

let observedActiveId = $state<string | null>(null);

$effect(() => {
  if (headings.length === 0) return;

  const headingElements = headings
    .map((h) => document.getElementById(h.id))
    .filter((el): el is HTMLElement => el !== null);

  if (headingElements.length === 0) return;

  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          observedActiveId = entry.target.id;
        }
      }
    },
    {
      rootMargin: "-80px 0px -60% 0px",
      threshold: 0,
    },
  );

  for (const el of headingElements) {
    observer.observe(el);
  }

  return () => observer.disconnect();
});

let effectiveActiveId = $derived(activeId ?? observedActiveId);
</script>

{#if headings.length > 0}
  <nav class={cn("toc", fontClass)} aria-label="Table of contents">
    {#each visibleHeadings as heading (heading.id)}
      {@const hasChildren =
        heading.level === 2 && h2sWithChildren.has(heading.id)}
      {@const isExpanded = expandedH2s.has(heading.id)}
      <a
        href={`#${heading.id}`}
        title={heading.text}
        class={`toc-item toc-level-${heading.level}${effectiveActiveId === heading.id ? " toc-active" : ""}`}
        onclick={(e) => {
          e.preventDefault();
          if (hasChildren) {
            toggleH2(heading.id);
          }
          onheadingclick(heading.id);
        }}
      >
        {heading.text}
        {#if hasChildren}
          <span class="toc-toggle ml-1 opacity-40">
            {isExpanded ? "\u25BE" : "\u25B8"}
          </span>
        {/if}
      </a>
    {/each}
  </nav>
{/if}

// src/components/TableOfContents.tsx
import { use, useMemo, useState } from "react";
import { SettingsContext } from "../contexts/SettingsContext";
import type { Heading } from "../lib/headings";
import { cn } from "../lib/utils";
import { FontFamilies } from "../schema";

interface TableOfContentsProps {
  headings: Heading[];
  activeId: string | null;
  onHeadingClick: (id: string) => void;
}

export function TableOfContents({
  headings,
  activeId,
  onHeadingClick,
}: TableOfContentsProps) {
  const settings = use(SettingsContext);
  const fontClass = settings
    ? settings.fontFamily === FontFamilies.SANS_SERIF
      ? "font-sans"
      : "font-serif"
    : undefined;

  const [expandedH2s, setExpandedH2s] = useState<Set<string>>(() => new Set());

  const h2sWithChildren = useMemo(() => {
    const result = new Set<string>();
    let currentH2: string | null = null;

    for (const heading of headings) {
      if (heading.level === 2) {
        currentH2 = heading.id;
      } else if (heading.level > 2 && currentH2) {
        result.add(currentH2);
      } else if (heading.level === 1) {
        currentH2 = null;
      }
    }
    return result;
  }, [headings]);

  const visibleHeadings = useMemo(() => {
    let currentH2: string | null = null;

    return headings.filter((heading) => {
      if (heading.level <= 2) {
        if (heading.level === 2) {
          currentH2 = heading.id;
        } else {
          currentH2 = null;
        }
        return true;
      }

      return currentH2 && expandedH2s.has(currentH2);
    });
  }, [headings, expandedH2s]);

  const toggleH2 = (id: string) => {
    setExpandedH2s((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  if (headings.length === 0) {
    return null;
  }

  return (
    <nav className={cn("toc", fontClass)} aria-label="Table of contents">
      {visibleHeadings.map((heading) => {
        const hasChildren =
          heading.level === 2 && h2sWithChildren.has(heading.id);
        const isExpanded = expandedH2s.has(heading.id);

        return (
          <a
            key={heading.id}
            href={`#${heading.id}`}
            title={heading.text}
            className={`toc-item toc-level-${heading.level}${activeId === heading.id ? " toc-active" : ""}`}
            onClick={(e) => {
              e.preventDefault();
              if (hasChildren) {
                toggleH2(heading.id);
              }
              onHeadingClick(heading.id);
            }}
          >
            {heading.text}
            {hasChildren && (
              <span className="toc-toggle ml-1 opacity-40">
                {isExpanded ? "▾" : "▸"}
              </span>
            )}
          </a>
        );
      })}
    </nav>
  );
}
