// src/components/ui/Dialog.svelte
<script lang="ts">
import { X } from "lucide-svelte";
import type { Snippet } from "svelte";
import { cn } from "../../lib/utils";

interface Props {
  open: boolean;
  onclose?: () => void;
  contentClass?: string;
  children: Snippet;
  header?: Snippet;
  headerActions?: Snippet;
}

let {
  open = $bindable(false),
  onclose,
  contentClass,
  children,
  header,
  headerActions,
}: Props = $props();

let dialogEl: HTMLDialogElement | undefined = $state();

$effect(() => {
  if (!dialogEl) return;

  if (open && !dialogEl.open) {
    dialogEl.showModal();
  } else if (!open && dialogEl.open) {
    dialogEl.close();
  }
});

$effect(() => {
  if (!dialogEl) return;

  const handleClose = () => {
    open = false;
    onclose?.();
  };

  dialogEl.addEventListener("close", handleClose);
  return () => dialogEl!.removeEventListener("close", handleClose);
});

function handleBackdropClick(e: MouseEvent) {
  if (e.target === dialogEl) {
    open = false;
    onclose?.();
  }
}

function handleCloseClick() {
  open = false;
  onclose?.();
}
</script>

<dialog
  bind:this={dialogEl}
  onclick={handleBackdropClick}
  class="backdrop:bg-black/20 dark:backdrop:bg-black/40 backdrop:backdrop-blur-sm bg-transparent p-0 m-auto max-w-none"
>
  {#if open}
    <div
      class={cn(
        "w-full bg-white/95 dark:bg-zinc-900/95 backdrop-blur-sm shadow-lg border border-zinc-200/40 dark:border-zinc-700/40 rounded-xl flex flex-col",
        contentClass,
      )}
    >
      {#if header}
        <div
          class="flex items-center justify-between pl-4 pr-12 py-3 border-b border-zinc-100 dark:border-zinc-800"
        >
          <h2 class="text-sm font-medium text-zinc-900 dark:text-zinc-100">
            {@render header()}
          </h2>
          {#if headerActions}
            {@render headerActions()}
          {/if}
        </div>
      {/if}

      <div class="flex-1 overflow-visible p-4">
        {@render children()}
      </div>

      <button
        type="button"
        onclick={handleCloseClick}
        class="absolute top-3 right-3 size-7 inline-flex items-center justify-center rounded-lg text-zinc-600 dark:text-zinc-400 hover:bg-zinc-100 dark:hover:bg-zinc-800"
      >
        <X class="w-4 h-4" />
      </button>
    </div>
  {/if}
</dialog>

// src/components/ui/dialog.tsx
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "lucide-react";
import { cn } from "../../lib/utils";
import { buttonVariants } from "./button";
import { textVariants } from "./text";

function Dialog({
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Root>) {
  return <DialogPrimitive.Root data-slot="dialog" {...props} />;
}

function DialogTrigger({
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Trigger>) {
  return <DialogPrimitive.Trigger data-slot="dialog-trigger" {...props} />;
}

function DialogPortal({
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Portal>) {
  return <DialogPrimitive.Portal data-slot="dialog-portal" {...props} />;
}

function DialogClose({
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Close>) {
  return <DialogPrimitive.Close data-slot="dialog-close" {...props} />;
}

function DialogOverlay({
  className,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Overlay>) {
  return (
    <DialogPrimitive.Overlay
      data-slot="dialog-overlay"
      className={cn(
        "fixed inset-0 z-50 bg-black/20 backdrop-blur-sm",
        className,
      )}
      {...props}
    />
  );
}

function DialogContent({
  className,
  children,
  showCloseButton = true,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Content> & {
  showCloseButton?: boolean;
}) {
  return (
    <DialogPortal>
      <DialogOverlay />
      <DialogPrimitive.Content
        data-slot="dialog-content"
        className={cn(
          "fixed top-1/2 left-1/2 z-50 w-full -translate-x-1/2 -translate-y-1/2",
          "bg-white/95 backdrop-blur-sm shadow-lg border border-zinc-200/40 rounded-xl",
          "flex flex-col animate-in",
          className,
        )}
        {...props}
      >
        {children}
        {showCloseButton && (
          <DialogPrimitive.Close
            data-slot="dialog-close"
            className={cn(
              buttonVariants({ variant: "ghost", size: "icon" }),
              "absolute top-3 right-3 size-7",
            )}
          >
            <X className="w-4 h-4" />
            <span className="sr-only">Close</span>
          </DialogPrimitive.Close>
        )}
      </DialogPrimitive.Content>
    </DialogPortal>
  );
}

function DialogHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="dialog-header"
      className={cn(
        "flex items-center justify-between px-4 py-3 border-b border-zinc-100",
        className,
      )}
      {...props}
    />
  );
}

function DialogTitle({
  className,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Title>) {
  return (
    <DialogPrimitive.Title
      data-slot="dialog-title"
      className={cn(
        textVariants({ variant: "section" }),
        "font-serif",
        className,
      )}
      {...props}
    />
  );
}

function DialogDescription({
  className,
  ...props
}: React.ComponentProps<typeof DialogPrimitive.Description>) {
  return (
    <DialogPrimitive.Description
      data-slot="dialog-description"
      className={cn(textVariants({ variant: "caption" }), "text-sm", className)}
      {...props}
    />
  );
}

function DialogBody({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="dialog-body"
      className={cn("flex-1 overflow-auto p-4", className)}
      {...props}
    />
  );
}

export {
  Dialog,
  DialogBody,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
};
