// src/components/ui/DropdownMenu.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { cn } from "../../lib/utils";

interface Props {
  open?: boolean;
  trigger: Snippet;
  align?: "start" | "end";
  contentClass?: string;
  children: Snippet;
}

let {
  open = $bindable(false),
  trigger,
  align = "start",
  contentClass,
  children,
}: Props = $props();

let containerEl: HTMLDivElement | undefined = $state();

function toggle() {
  open = !open;
}

function close() {
  open = false;
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Escape" && open) {
    e.stopPropagation();
    close();
  }
}

$effect(() => {
  if (!open) return;

  function handleClickOutside(e: MouseEvent) {
    if (containerEl && !containerEl.contains(e.target as Node)) {
      close();
    }
  }

  document.addEventListener("mousedown", handleClickOutside);
  return () => document.removeEventListener("mousedown", handleClickOutside);
});
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  bind:this={containerEl}
  class="relative inline-block"
  onkeydown={handleKeydown}
>
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <div onclick={toggle} role="button" tabindex="-1">
    {@render trigger()}
  </div>

  {#if open}
    <div
      class={cn(
        "absolute top-full mt-1 z-50 min-w-[8rem] overflow-hidden rounded-xl py-1",
        "bg-white/95 dark:bg-zinc-900/95 backdrop-blur-sm shadow-lg border border-zinc-200/40 dark:border-zinc-700/40",
        align === "end" ? "right-0" : "left-0",
        contentClass,
      )}
    >
      {@render children()}
    </div>
  {/if}
</div>

<script lang="ts" module>
  export { default as DropdownMenuItem } from "./DropdownMenuItem.svelte";
  export { default as DropdownMenuSeparator } from "./DropdownMenuSeparator.svelte";
</script>

// src/components/ui/DropdownMenu.tsx
import { createContext, use, useCallback, useRef, useState } from "react";
import { useClickOutside } from "../../hooks/useClickOutside";
import { cn } from "../../lib/utils";

interface DropdownState {
  open: boolean;
  setOpen: (open: boolean) => void;
}

const DropdownContext = createContext<DropdownState>({
  open: false,
  setOpen: () => {},
});

function DropdownMenu({
  open: controlledOpen,
  onOpenChange,
  children,
}: {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  children: React.ReactNode;
}) {
  const [internalOpen, setInternalOpen] = useState(false);
  const isControlled = controlledOpen !== undefined;
  const open = isControlled ? controlledOpen : internalOpen;
  const setOpen = useCallback(
    (v: boolean) => {
      if (!isControlled) setInternalOpen(v);
      onOpenChange?.(v);
    },
    [isControlled, onOpenChange],
  );

  const ref = useRef<HTMLDivElement>(null);
  useClickOutside(ref, () => setOpen(false), open);

  return (
    <DropdownContext value={{ open, setOpen }}>
      <div ref={ref} className="relative inline-block">
        {children}
      </div>
    </DropdownContext>
  );
}

function DropdownMenuTrigger({
  asChild,
  children,
  ...props
}: {
  asChild?: boolean;
  children: React.ReactNode;
} & React.ButtonHTMLAttributes<HTMLButtonElement>) {
  const { open, setOpen } = use(DropdownContext);

  if (
    asChild &&
    children &&
    typeof children === "object" &&
    "props" in children
  ) {
    const child = children as React.ReactElement<Record<string, unknown>>;
    return (
      <child.type
        {...child.props}
        onClick={(e: React.MouseEvent) => {
          setOpen(!open);
          if (typeof child.props.onClick === "function") child.props.onClick(e);
        }}
      />
    );
  }

  return (
    <button type="button" onClick={() => setOpen(!open)} {...props}>
      {children}
    </button>
  );
}

function DropdownMenuContent({
  className,
  align = "start",
  children,
}: {
  className?: string;
  align?: "start" | "end";
  children: React.ReactNode;
}) {
  const { open } = use(DropdownContext);
  if (!open) return null;

  return (
    <div
      className={cn(
        "absolute top-full mt-1 z-50 min-w-[8rem] overflow-hidden rounded-xl py-1",
        "bg-white/95 dark:bg-zinc-900/95 backdrop-blur-sm shadow-lg border border-zinc-200/40 dark:border-zinc-700/40",
        align === "end" ? "right-0" : "left-0",
        className,
      )}
    >
      {children}
    </div>
  );
}

function DropdownMenuItem({
  className,
  variant = "default",
  onSelect,
  children,
  ...props
}: {
  className?: string;
  variant?: "default" | "destructive";
  onSelect?: () => void;
  children: React.ReactNode;
  title?: string;
}) {
  const { setOpen } = use(DropdownContext);

  return (
    <button
      type="button"
      className={cn(
        "w-full px-3 py-1.5 text-left text-sm outline-none select-none transition-colors duration-150 flex items-center gap-2 cursor-default",
        variant === "default" &&
          "text-zinc-600 dark:text-zinc-400 hover:bg-zinc-50 dark:hover:bg-zinc-800 hover:text-zinc-900 dark:hover:text-zinc-100",
        variant === "destructive" &&
          "text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-950 hover:text-red-700 dark:hover:text-red-300",
        "[&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-3.5",
        className,
      )}
      onClick={() => {
        onSelect?.();
        setOpen(false);
      }}
      {...props}
    >
      {children}
    </button>
  );
}

function DropdownMenuSeparator({ className }: { className?: string }) {
  return (
    <div className={cn("my-1 h-px bg-zinc-100 dark:bg-zinc-800", className)} />
  );
}

export {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
};
